### ISSUE TITLE
Super Bowl support?

### ISSUE THREAD

**Issue by Marfinho** [zacs/ha-nfl#12]
Hi :)

Just stumbled across your integration and installed it directly. Unfortunately the entity stays empty. Is this because of the Super Bowl? I'm fan of the Rams so I'd love to see the upcoming Super Bowl on my HA. 

Am I to stupid or are you just don't grab the data for the sb? 

Cheers and thank you in advance,
Sven

**Comment by gonzotek** [comment]
Jumping in here (not the principal developer, just an enthusiastic user). The espn data (http://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard) the integration uses still reflects last week's pro bowl game.  During the regular season, the games for the week would usually change over on Wednesdays, so (hopefully) the LAR and CIN team data will show up tomorrow.

**Comment by Marfinho** [comment]
Ah, thanks mate. Makes totally sense. Also looked into the data of ESPN but just overlooked it and was totally irritated seeing somewhere Kyler Murray and then just closed it. I'm not interested in ProBowl and didn't noticed that the reason for Murray showing up was the PB.
I'll just sit and wait :)

**Comment by gonzotek** [comment]
> was totally irritated seeing somewhere Kyler Murray and then just closed it

:laughing: All good!  If for some reason it's not working by the end of the day tomorrow (EST time zone for me), I'll start looking into why will update this issue.

**Comment by gonzotek** [comment]
The Rams/Bengals 2022 Super Bowl game data is available and entities are populating with the relevant data for either team acronym in Home Assistant, so I believe we're good to go for Sunday :-)

**Comment by zacs** [comment]
Thanks to @gonzotek for confirming! Closing an issue because it just works is the best.
