### ISSUE TITLE
API returning not found

### ISSUE THREAD

**Issue by bgulla** [zacs/ha-nfl#13]
Ever since this monday, my NFL integration is returning 'NOT FOUND' (entity state) and 'null' for all attributes. I installed a fresh integration on a new HA instance and the problem still persisted. 

The queries for BAL and HOU both came back with NOT FOUND, so I do not believe this is isolated to a team.

**Comment by mattwalden014** [comment]
Also having the same issue

**Comment by bgulla** [comment]
`http://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard` is returning a 404 and it's the primary API endpoint listed in `const.py`

**Comment by zacs** [comment]
It looks like the API only goes a week in, so only data for JAX and OAK exists, so I think this is by design. Once that game is over we will see what

**Comment by zacs** [comment]
> `http://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard` is returning a 404 and it's the primary API endpoint listed in `const.py`

I get data for it (tried a few hours ago and again just now) just fine, but it's limited to the first preseason game (since it's ~a week earlier than the rest).

**Comment by mattwalden014** [comment]
Thanks @zacs. They must've changed how far in advance it's publishing games on the API as I had previously been seeing other preseason games.

**Comment by zacs** [comment]
> Thanks @zacs. They must've changed how far in advance it's publishing games on the API as I had previously been seeing other preseason games.

Interesting! To be honest I haven't paid attention to my sensors lately (maybe I should keep it that way since I'm a Seattle fan...), so I didn't notice. My guess is that once we got within 7 (or some similar number) days of the first game the ESPN system snapped into "in season" mode. 

I'll try at least adding OAK/JAX to get started testing if there are any format changes this year.

**Comment by zacs** [comment]
@bgulla please re-open if you see any more 404s. Suspecting we may have seen some as a result of ESPN going into "in-season mode" and maybe deploying some new code, etc. Hopefully won't see again this season.
