### ISSUE TITLE
Sensor unavailable during delayed start of  2022 JAX vs LAR Preseason game

### ISSUE THREAD

**Issue by gonzotek** [zacs/ha-nfl#14]
I managed to capture the json during the game delay last night.  I didn't have the chance to watch live, but this morning all of the sensor data looks as correct as can be (allowing for the expected nulls for the in-game-only attributes).  

Anyway, I think the relevant issue with the unavailable during the delay is in the event status fields.  The state was "in", but several others showed as delayed:
`
                    "status": {
                        "clock": 900.0,
                        "displayClock": "15:00",
                        "period": 1,
                        "type": {
                            "id": "7",
                            "name": "STATUS_DELAYED",
                            "state": "in",
                            "completed": false,
                            "description": "Delayed",
                            "detail": "Delayed",
                            "shortDetail": "Delayed"
                        }
                    }
`
I think I could probably work out a fix, but I won't have a chance to dig into the code to troubleshoot further for at least a few weeks due to work commitments, so wanted to open the issue in case anyone else ran across this as well and wanted to pick it up.

[scoreboard.json.txt](https://github.com/zacs/ha-nfl/files/9268292/scoreboard.json.txt)

**Comment by zacs** [comment]
Thanks for grabbing the JSON! I think that's an easy fix, should be a little hacky but can look at the text fields for the word "delayed" and go from there. I'm also pretty slammed with work but will try to get to it this weekend.

**Comment by zacs** [comment]
Closing since AFAIK this was an ESPN issue with which games they listed. If you still notice teams missing, please raise another issue!
