### ISSUE TITLE
Error fetching Browns data: list index out of range

### ISSUE THREAD

**Issue by Jefe2** [zacs/ha-nfl#16]
The API apparently changed from last season.  I have three NFL integrations installed and they worked very well last season. This week, the Steelers-Seahawks game is showing up on one card, but I’m getting an error for the other 2 integrations I have installed:
```
Error fetching Ravens data: list index out of range
Error fetching Browns data: list index out of range
```
There’s no hurry in taking a look, it’s only pre-season 😉
Thanks!

**Comment by gonzotek** [comment]
I think it's probably the same issue I found yesterday: https://github.com/zacs/ha-nfl/pull/15
I put in a pull request and @zacs accepted it but he'll need to do a new release for hacs to pick it up, I think.  I logged another new issue, https://github.com/zacs/ha-nfl/issues/14 from last weeks delayed game, that neither he nor I have gotten around to fixing yet, so he may be holding until he can (or someone) has the time to fix as well.  If you're comfortable editing python files, you can look at the pull request and make the change to your local install pretty easily until there's a new release.

**Comment by Jefe2** [comment]
Many thanks. I applied the change you suggested and it works well.  All three teams/games are displayed now...  And I learned something.

**Comment by zacs** [comment]
Cutting the release now, just wanted to see if there were any more bugfixes to include, but seems mostly quiet 🤞.
