### ISSUE TITLE
Wrong text

### ISSUE THREAD

**Issue by JGNi** [zacs/ha-nfl#24]
The text in HA hasn't been changed from the weather forked edition.

**Comment by gonzotek** [comment]
In Home Assistant, or the HACS information popup for the integration?  Searching the repo for 'weather', I only find two files, one is the [nws_alerts_custom_package.yaml](https://github.com/zacs/ha-nfl/blob/master/packages/nws_alerts_custom_package.yaml) in the packages folder, the other is the [info.md](https://github.com/zacs/ha-nfl/blob/master/info.md) file at the repo root.  This looks like it is what is displayed in the HACS information, and probably is what needs to be fixed.  It looks like the same basic information as the readme.md, so a simple fix would be to just mirror the content from readme to info.

The package yaml could probably just be dropped, as looking at the contents, I'm not sure there's anything worth salvaging/porting to over to NFL.

**Comment by firstof9** [comment]
Just copy the readme.md to info.md or change the hacs.json to use the readme instead of info.md

**Comment by gonzotek** [comment]
Pull request created: https://github.com/zacs/ha-nfl/pull/25
