### ISSUE TITLE
For discussion: Packages directory and some other contributions

### ISSUE THREAD

**Issue by gonzotek** [zacs/ha-nfl#29]
I was thinking of submitting a PR to remove the packages directory...it's a remnant of the NWS alerts component, and doesn't seem to have anything worth salvaging for NFL. 

On somewhat a related topic, I was also thinking of contributing the mobile_app notification blueprint I built to the NFL repo as well.  Feel like it really belongs here rather than on it's own page.

I also have a few more personal automations I could probably develop into either blueprints or cleaned-up automations for sharing on the wiki. Btw, besides opening an issue - how would I contribute to the wiki? It doesn't seem to be editable if you're not a project collaborator.

(not gonna lie...I'm trying to get to 4 PRs for Hacktoberfest lol...but I do want to make them all count for something!)

**Comment by zacs** [comment]
Go for it! My initial goal was to put some useful things in `packages/` but as you say, no one has done that and I honestly don't have enough time to at the moment. 

If there are other things you'd like to add like the mobile notifications, I think they'd be more than welcome. Are they code? If so, is there a best practice on where to add them (eg. a `blueprints/` folder)? If we need to invent something I'm fine with that!

**Comment by zacs** [comment]
Closed in #31 and #32 -- appreciate you @gonzotek!
