### ISSUE TITLE
Integration Requires internet acces to 104.16.125.175 on client.

### ISSUE THREAD

**Issue by brokenarrow03** [zacs/ha-nfl#34]
I have this integration in my home assistant and it works really well. However I have some devices, samsung tablets, that have no access to the internet and connect to home assistant internally only. When I try to access the dashboard that is configured in home assistant, which has internet access, the entity: sensor.nfl reports as "custom element does not exist" on the tablet dashboard. I have validated this by allowing internet access, then working backward by allowing only certain IP addresses.

This IP address is used by Cloudfare, and I have attached a screenshot of the error! Thank you! 
![Screenshot_20221109-145229_Home Assistant](https://user-images.githubusercontent.com/64863374/200984582-fe4e8325-f388-44f0-b550-928d63b97c52.jpg)

**Comment by zacs** [comment]
This is very weird. Can you paste in the contents of sensor.nfl from the States tab in the Developer part of the UI when the internet is disabled? 

I think this is an error with the card itself. @D34DC3N73R does your card load images or something from the internet?

**Comment by brokenarrow03** [comment]
Ah I see where the card itself is most likely at fault. After a quick test, both of my sensor.nfl both still say PRE after checking them when the internet was blocked. I appreciate the insight!

**Comment by D34DC3N73R** [comment]
Yes, it grabs the team logos from ESPN. I suppose I could package them with the card itself, but I haven't fully considered that yet.

**Comment by brokenarrow03** [comment]
@D34DC3N73R would you like me to open an issue on your page? I understand that it pulls images from ESPN, but I dont understand why the device that connects to home assistant needs that access when home assistant has the capability to get the images.

**Comment by brokenarrow03** [comment]
I do appreciate both of your comments!

**Comment by gonzotek** [comment]
Suggestion/thought:
Could the integration pull and cache the images on demand to the home
assistant server, for the card to then access over local area network? This
way the images wouldn't need to be packaged with either the card or the
integration and the client doesn't need internet. Should also avoid any
copyright issues as well since then it's only temporarily cached data.

**Comment by brokenarrow03** [comment]
@gonzotek I agree, I can assist as needed as well. That is what I thought would happen as far as image flow, or if the request comes from a client, home assistant goes out to get it and gives it to the client. Cache is nice, but not necessary!

**Comment by D34DC3N73R** [comment]
The integration only provides team logo image URLs. The frontend card grabs and displays the URLs using the client browser. My main concern is redistribution/packaging, so if server caching is a viable solution, it would be ideal in my opinion. 

With that said, if this isn't a common request it would be possible to edit the card to use a manually downloaded directory of team images. With some work it would also be possible to add `local_image: true` and `image_path: /path/to/team/logos` variables to the card itself, but that would still require the user to manually save the images in an accessible location on the HA server. I'm open to other suggestions.

**Comment by zacs** [comment]
Closing since this is related to the card, and not the integration itself.
