### ISSUE TITLE
NFL Game Score Light Color Flasher (Feature Request)

### ISSUE THREAD

**Issue by baj24** [zacs/ha-nfl#36]
Is it possible to add a feature in this blueprint to return the lights to the previous state they were in prior to this automation running?  I think it's possible with the snapshot_entities parameter.

**Comment by gonzotek** [comment]
It should do that already. See https://github.com/zacs/ha-nfl/blob/master/blueprints/nfl-game-score-lights.yaml#L65 and the final action in the sequence  should restore the state.  But I have definitely observed some occasions (with both Hue and wled light types) where the state doesn't return perfectly to what it was when the scene was captured.  I do not know why it mostly works, but sometimes doesn't...at a guess, it could be a race condition. Maybe I could try adding a slight delay action after scene capture call.

**Comment by baj24** [comment]
> It should do that already. See https://github.com/zacs/ha-nfl/blob/master/blueprints/nfl-game-score-lights.yaml#L65 and the final action in the sequence should restore the state. But I have definitely observed some occasions (with both Hue and wled light types) where the state doesn't return perfectly to what it was when the scene was captured. I do not know why it mostly works, but sometimes doesn't...at a guess, it could be a race condition. Maybe I could try adding a slight delay action after scene capture call.

I've noticed that they go back to the color they were before, but if the lights were off before the automation runs, they don't turn back off.

**Comment by gonzotek** [comment]
Interesting. I don't think I tested for that since the main light I use is always on during the games I watch(a behind the tv lightstrip).  I'll see if there's anything that I can do about that.  What HA integration are your lights, out of curiosity (I'm working mostly with Hue and wled).

**Comment by baj24** [comment]
All of my lights are Hue lights.

**Comment by gsakel1** [comment]
Could a feature be added to flash only on touchdowns for this blueprint?
