### ISSUE TITLE
hass.config_entries.async_setup_platforms is scheduled to be removed in 2023.03

### ISSUE THREAD

**Issue by vasqued2** [zacs/ha-nfl#37]
A guardian angel gave me a heads up that `hass.config_entries.async_setup_platforms` is being deprecated in HA 2023.03 so I wanted to pass it along to  you.

[Here's the pull request](https://github.com/vasqued2/ha-teamtracker/pull/65) in my repo to give you an idea of what needs to change.

Details of the change here:  https://developers.home-assistant.io/blog/2022/07/08/config_entry_forwards/

**Comment by zacs** [comment]
Thank you for the heads up, and thanks @D34DC3N73R for the PR #41 which fixes this.
