### ISSUE TITLE
adding several tournaments to team

### ISSUE THREAD

**Issue by Jase53** [zacs/ha-nfl#39]
Following a team in europe they can play in several tournaments. Fx. MNC plays in the Premier league, champions league and the FA cup [local cup tournamant]. it could be nice to add several tournaments fx like"" EPL, CL" so you dont need a card for each tournament your team plays in. :) thanks for the great work on this so far.

**Comment by zacs** [comment]
I believe you are looking for https://github.com/vasqued2/ha-teamtracker
