### ISSUE TITLE
automation state trigger by "last play" attribute

### ISSUE THREAD

**Issue by jenniferlee1818** [zacs/ha-nfl#48]
When setting up my automation state trigger, "last_play" is missing from the attribute dropdown.

**Comment by zacs** [comment]
My guess is that when the attr is unavailable, it won't show up in the automations UI. I would just choose another attribute when you make the automation in the UI, then go into YAML editing mode and change nfl.whatever_you_randomly_picked to nfl.last_play.

**Comment by jenniferlee1818** [comment]
Thanks that works.  I guess I never knew that unavailable attributes don't show up in the UI.  And in the attribute dropdown is "Attribution" just something odd I noticed.
