### ISSUE TITLE
Team Color RGB not set

### ISSUE THREAD

**Issue by olgru** [zacs/ha-nfl#51]
Already since last season the integration is not working for NFL Team PHI. Seems to be a problem with ColorRGB.
This is the outcome of the used Automation template:
-----------------------------------------------------------------------
Ausgeführt: 13. Oktober 2024 um 21:25:50
Fehler: None for dictionary value @ data['rgb_color']
Ergebnis:

params:
  domain: light
  service: turn_on
  service_data:
    rgb_color: ''
    entity_id:
      - light.sofalampe
      - light.stehlampe
  target:
    entity_id:
      - light.sofalampe
      - light.stehlampe
running_script: false

-------------------------------------------------------------------
This is the entry of "my" team_phi object:
-------------------------------------------------------------------
attribution: Data provided by ESPN
date: 2024-10-13T17:00Z
kickoff_in: 3 hours ago
quarter: null
clock: null
venue: Lincoln Financial Field
location: Philadelphia, PA
tv_network: FOX
odds: null
overunder: null
possession: null
last_play: null
down_distance_text: null
team_abbr: PHI
team_id: 21
team_name: Eagles
team_record: 3-2
team_homeaway: home
team_logo: https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/phi.png
team_colors: #06424d, #000000
team_colors_rgb: 
- - 6
  - 66
  - 77
- - 0
  - 0
  - 0

team_score: 20
team_win_probability: null
team_timeouts: 3
opponent_abbr: CLE
opponent_id: 5
opponent_name: Browns
opponent_record: 1-5
opponent_homeaway: away
opponent_logo: https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/cle.png
opponent_colors: #472a08, #ff3c00
opponent_colors_rgb: 
- - 71
  - 42
  - 8
- - 255
  - 60
  - 0

opponent_score: 16
opponent_win_probability: null
opponent_timeouts: 3
last_update: 2024-10-13 22:05:00+02:00
icon: mdi:football
friendly_name: team_phi

**Comment by zacs** [comment]
What automation template are you using? `team_colors` and `team_colors_rgb` are both present in your sensor, so there is nothing wrong with the component.
