### ISSUE TITLE
no card in integrations section.

### ISSUE THREAD

**Issue by sunsgs** [zacs/ha-nfl#8]
It seems that there are no integrations in configuration->integration for NFL

**Comment by zacs** [comment]
What version of HA are you running? Was there a card there before? Did you setup via UI or config yaml? How many fingers am I holding up?

**Comment by SnowKing25** [comment]
I'm also seeing this error on start up. Started seeing it after updating to version v0.3, installed via HACS. I also updated to HA 2021.12.9 at the same time. I have my config set up via the UI, not manually with yaml. Full HA error log is:

2022-01-15 17:14:19 ERROR (MainThread) [homeassistant.setup] Setup failed for nfl: Integration not found.

**Comment by zacs** [comment]
Hmm, is the code actually still there? That's the error you'd see if it had been deleted from the custom_components folder.

**Comment by SnowKing25** [comment]
Yeah, I still see the code in the custom_components folder. And, perhaps to add some context to the title, when I try to search for nfl in the ui for the integration, I don't get any results.

I also tried to add to the config file manually, and I get "Platform error sensor.nfl - Integration 'nfl' not found."

I can try to uninstall/re-install?

**Comment by zacs** [comment]
Does this still happen @sunsgs ? I would hope an uninstall/reboot/reinstall would work here.
